### ISSUE TITLE
Can't install on 1.16.2 from master (with 1.16 fix)

### ISSUE THREAD

**Issue by hexa00** [polyaxon/polyaxon-chart#52]
Hi,
   Doing: 
```
    git clone https://github.com/polyaxon/polyaxon-chart
    helm dependency update ./polyaxon
    helm install ./polyaxon --name=polyaxon --namespace=polyaxon -f ../polyaxon/config.yaml  --dry-run --debug
```
I get : 

```
[debug] Created tunnel using local port: '38219'

[debug] SERVER: "127.0.0.1:38219"

[debug] Original chart version: ""
[debug] CHART PATH: /.../polyaxon-chart/polyaxon

Error: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
   
```

That's on k8s 1.16.2 using microk8s 
```
kubectl version 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

```

This is with master head is : 
```
commit 5b5b5f8b52619f98defadc4fcb647abeb0db3993 (HEAD -> master, origin/master, origin/HEAD)
Author: Rinat Shigapov <rinatshigapov@gmail.com>
Date:   Tue Oct 22 20:00:50 2019 +0300

    add K8S 1.16 support (#51)
    
    * add k8s 1.16 support
    
    * streams is unready when api server uses SSL+NodePort
    
    * revert postgres dependency
```

**Comment by hexa00** [comment]
cc @DXist @mouradmourafiq

**Comment by mouradmourafiq** [comment]
I just tried master with a client : `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`

unfortunately I don't have a k8s server with 1.16, but I am afraid that the problem could be one of the dependencies, probably postgres.

**Comment by DXist** [comment]
Yes, deprecated syntax is removed from Postgresql chart only in recent version but it seems that Polyaxon tests don't work with the newest Postgresql.

Personally I use external Postgres instance managed by Google Cloud Platform and didn't hit this problem.

**Comment by hexa00** [comment]
Thanks for narrowing it down to postgresql :) 

I'm not tied to 1.16 so I'll try 1.15 for now... still hope it gets resolved somehow since it breaks the default documentation for microk8s

**Comment by mouradmourafiq** [comment]
k8s 1.16 is breaking several things, there's also a problem with helm I hope that it was solved upstream, see [issue](https://github.com/polyaxon/polyaxon/issues/601).

**Comment by vakker** [comment]
So the solution is to downgrade or is there another solution on the way?
I have helm 3.0.2, is it planned to work with that or only helm 2?

**Comment by mouradmourafiq** [comment]
v0.6 has been pushed, making compatible with k8s 1.16.

> I have helm 3.0.2, is it planned to work with that or only helm 2?
You should be able to use helm 3 without relying on polyaxon cli by using the helm cli directly. The [docs](https://docs.polyaxon.com/setup/kubernetes/#deploy) have been updated with the Helm command to use.

closing the issue.

**Comment by vakker** [comment]
@mouradmourafiq with chart v0.6 and Kubernetes 1.17 I'm still getting:
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Comment by mouradmourafiq** [comment]
You need to provide you own postgres, and disable the built-in one, unfortunately it's no possible to update that dependency, because other people already running the platform with built-in database, will have non-backward compatible update.

The postgres db dependency will be updated in v1.x.
